// flow-typed signature: 8ba626e009a274df73c529678ac0da05
// flow-typed version: <<STUB>>/jspdf_v1.4.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jspdf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jspdf' {
  declare module.exports: any;
}
